name: panda-market

services:
  db:
    image: postgres:latest
    container_name: panda-market-db
    environment:
      POSTGRES_USER: codeitdba
      POSTGRES_PASSWORD: codeit
      POSTGRES_DB: codeit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codeitdba -d codeit"]
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  migrate:
    image: panda-market:latest
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    entrypoint:
      [
        "sh",
        "-lc",
        "npx prisma migrate deploy --schema=/app/prisma/schema.prisma",
      ]
    restart: "no"

  api:
    build:
      context: .
      pull: true
      tags:
        - panda-market:latest
        - panda-market:1.1.0
    image: panda-market:latest
    container_name: panda-market-api
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/app/uploads
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: panda-market-nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
  upload-data:
