### register
POST http://localhost:{{$dotenv PORT}}/auth/register
Content-Type: application/json; charset=UTF-8

{
    "email":"cidaja7735@binafex.com",
    "nickname": "testuser",
    "password": "testpassword"
}

### local login
POST http://localhost:{{$dotenv PORT}}/auth/local/login
Content-Type: application/json; charset=UTF-8

{
    "email": "cidaja7735@binafex.com",
    "password": "testpassword"
}

### logout
POST http://localhost:{{$dotenv PORT}}/auth/logout

### refresh token
POST http://localhost:{{$dotenv PORT}}/auth/refresh
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}

{
    "email": "cidaja7735@binafex.com",
    "password": "testpassword",
    "refreshToken": "{{$dotenv REFRESH_TOKEN}}"
}

# 토큰을 만료시키려면, 오직 하나의 토큰만 유효하게 하도록 DB에 관련 정보를 저장하거나 블랙리스트 목록을 통해서 관리할 수 있도록 한다.