# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: sprint11 CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: panda_market
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres -d panda_market"
          --health-interval=5s --health-timeout=5s --health-retries=20

    env:
      NODE_ENV: test
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/panda_market?schema=public"
      PORT: "3000"
      JWT_ACCESS_TOKEN_SECRET: "test-access-secret-32bytes-min"
      JWT_REFRESH_TOKEN_SECRET: "test-refresh-secret-32bytes-min"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install deps
        run: npm install 
      - name: Prisma migrate
        run: npx prisma migrate dev
      - name: Run tests
        run: npm run test

